### ISSUE TITLE
Problems with Energy Value System

### ISSUE THREAD

**Issue by pahimar** [pahimar/Equivalent-Exchange-3#990]
Master ticket to track current issues with the energy value system in the 0.3.* set of releases

**Comment by pahimar** [comment]
#986 
#978 
#968
#963 
#952 
#950 
#937 
#935 
#926
#925 
#906
#905 
#900 
#897 
#888 
#856 
#830 
#828 
#823 
#821 
#820 
#783

**Comment by pahimar** [comment]
#967

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990

**Comment by RoloEdits** [comment]
isnt this #990?

**Comment by pahimar** [comment]
Derp

**Comment by RoloEdits** [comment]
:P

**Comment by pahimar** [comment]
#953

**Comment by pahimar** [comment]
#933

**Comment by pahimar** [comment]
#923

**Comment by nightscloud2** [comment]
I've went in and used the command /ee3 set-energy-value-current-item pre 4000 while holding a diamond. i also ran the same command using /ee3 set-energy-value-current-item post 4000. I changed the value of the diamond from the original value of around 8000 to 4000. When I first start my world there are no values automatically set.  When i restart my world, all of the values for items using the diamond get values, however, it doesn't calculate from 4000, it still thinks the value of the diamond is 8000 and makes swords worth 16000 instead of 8000. I dont want to go and fix every single value for armor, and tools using ores. What should i do?

**Comment by RoloEdits** [comment]
Post means that nothing else that uses it is calculated. Post = after calculation. I would only use pre. Also try to use the ee3 add-on ee3 helper, it has a command that lets you recalculate the values in game, it is very useful.

**Comment by gravestristen** [comment]
so has this been fixed yet because when i do one thing to fix one mod it breaks the emc values for a different mod

**Comment by pahimar** [comment]
@gravestristen if it was fixed this master ticket would be closed

**Comment by AlphonseSantoro** [comment]
To fix some of the EMC problems I removed chisel completely.

 I still have following mods installed: ( Saw that some had problems when these were installed)
extrautilities-1.2.12
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112
buildcraft-7.1.16

TE's copper tin, etc, have EMC. so I would think chisel is definitely the culprit here

**Comment by KimJohngRaff** [comment]
So I've noticed a few things regarding this bug while playing a pack containing EE3 for the past year or so. Weirdly it basically seems to be random for me whether or not this bug exists. Sometimes I log in and all of my EMC values are perfectly fine. Other times I log in and every item that is crafted using cobble, wood, or blaze powder has no EMC value. It appears to me that extra utilities is responsible for the cobble and wood, and thaumcraft is responsible for the blaze powder. I originally though this bug was a result of dynamic EMC simply not being able to deal with mods adding the ability to craft things that have ore-dics with vanilla items that have hard-coded EMC values but if that's the case, the EMC values should always be broken as long as the culprit mods are installed so I really don't know whats going on here.

Important info about my pack: 
- I'm using FTB launcher
- I'm playing single player so the server is reset every time I log in.
- I have  S:energyvalues.regenerateEnergyValuesWhen=Always
- Despite this, I only notice a change in whether or not the bug is present when I add or remove mods from the mods folder, but It doesn't matter if the mod being added/removed is a culprit mod. (one time I updated Optifine and that made the bug appear, then a few days later I added storage drawers and the bug disappeared)
- Disabling/enabling mods using the FTB launcher seems to have no effect.
- non-vanilla metals have never worked in my pack
- cobble, wood, and blaze powder sometimes work

This leads me to believe that the existence of the bug may change based on exactly when EE3 initializations are executed relative to other mods' initializations in the pack as this order could change whenever a mod is added or removed from the pack.

I don't know if this is useful information but I hope it is.

**Comment by pahimar** [comment]
So many of these issues are out of date when compared to the new code. I think mostly all of the above issues are now resolved but I could be wrong.

I'm going to close this master ticket, and ask that new issues be reported in new tickets. Thank you all for your patience while I worked these issues out.

**Comment by SegFault22** [comment]
I'm still having the problem, even with the latest released version.
Diamonds turn into ash in the calcinator/calciner.
I checked the EMC value of diamond and it exists, but the value for minium dust does not exist.
I went into a creative world and set the emc-value of minium dust to 8192, and this was written to the energy values files (tried pre and post) but it is not loaded into any world as such (still no exchange energy value).
Since it isn't being caused by the entry simply not existing in any of the data files, and attempting to set the energy value manually does nothing even though the chat command appears to work, I would say that this bug is still very much alive. It may not be the same bug, but the "symptoms" are nearly identical.

I don't want to be a traitor and use ProjectE, because I already made an aludel and two calciners/calcinators, and it isn't nice to be a traitor. Also, those light-powered condensers are too OP. The mod does have alchemy-related chests that can convert items automatically, but I got an addon for EE3 which does that a little bit differently, so I don't yet have any good reason to remove EE3 and watch as those precious calciners/aludel get whisked away by the Forge Teleport-Unknown-Items-To-The-Void feature.
